### ISSUE TITLE
[feature-request] Command prefixes should be seperated by spaces, not by character

### ISSUE THREAD

**Issue by RecapTimeSquad** [AmanoTeam/UserLixo#2]
## Description

If an user configured their prefixes with spaces (e.g. `rt! >`), the userbot should be parse them  like this:
* `rt!help`
* `>commands`

but not this:
* `rhelp`
* `tcommands`
* `!plugins`
* ` userinfo`
* `>ping`

## Related Case

* https://t.me/UserLixoChat/8521

---
This account is an placeholder for team members at @MadeByThePinsHub. This issue is made by @AndreiJirohHaliliDev2006.

**Comment by AndrielFR** [comment]
Fixed on https://github.com/AmanoTeam/UserLixo/commit/a7a4b664d552b2e3e8fa1cf9241e4f8263bebd66.

**Comment by edubr029** [comment]
@AndrielFR boa andriel
